package com.jennifer.sportsmeeting.bean;

import java.io.Serializable;

public class Manager implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.m_username
     *
     * @mbg.generated Wed Feb 19 15:17:02 CST 2020
     */
    private String mUsername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.m_password
     *
     * @mbg.generated Wed Feb 19 15:17:02 CST 2020
     */
    private String mPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table manager
     *
     * @mbg.generated Wed Feb 19 15:17:02 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.m_username
     *
     * @return the value of manager.m_username
     *
     * @mbg.generated Wed Feb 19 15:17:02 CST 2020
     */
    public String getmUsername() {
        return mUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.m_username
     *
     * @param mUsername the value for manager.m_username
     *
     * @mbg.generated Wed Feb 19 15:17:02 CST 2020
     */
    public void setmUsername(String mUsername) {
        this.mUsername = mUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.m_password
     *
     * @return the value of manager.m_password
     *
     * @mbg.generated Wed Feb 19 15:17:02 CST 2020
     */
    public String getmPassword() {
        return mPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.m_password
     *
     * @param mPassword the value for manager.m_password
     *
     * @mbg.generated Wed Feb 19 15:17:02 CST 2020
     */
    public void setmPassword(String mPassword) {
        this.mPassword = mPassword;
    }
}